### ISSUE TITLE
compilation error in last 1.2.2

### ISSUE THREAD

**Issue by sylus28** [Firesped/Marlin-Raise3D-N-Series-Unofficial#1]

**Comment by sylus28** [comment]
[Sans titre.txt](https://github.com/Firesped/Marlin-Raise3D-N-Series-Unofficial/files/1164722/Sans.titre.txt)

**Comment by sylus28** [comment]
here my config.h
[Configuration .txt](https://github.com/Firesped/Marlin-Raise3D-N-Series-Unofficial/files/1164764/Configuration.txt)

**Comment by Firesped** [comment]
let me check something, I've got like 2 versions of 1.2.2 because my printer is in a separate folder. need to make sure there are no issues with the main version

**Comment by Firesped** [comment]
Arduino IDE 1.8.2 has no issues compiling it on my system. 

looking at the sans titre.txt. it looks like you have dubplacate files on a number of things. Marlin_main.cpp and Marlin_main 2.cpp. let me make sure this is not on GitHub this way.

**Comment by sylus28** [comment]
Try again with fresh config.h and it works now
I will test it when i return
